export type ModelVariant = {
  id: string;
  name: string;
  filename: string;
  size: string;
  vram: number;
  vramMax?: number;
  type: "full" | "distilled" | "fp8" | "lora";
  hfUrl: string;
  description: string;
  badge?: string;
  recommendation?: string;
  isNew?: boolean;
  // Per-model differentiation content. Rendered conditionally on detail pages.
  // Only filled for high-impression files; others fall back to type-level defaults.
  technicalNotes?: string;
  whenToChoose?: string;
  knownIssues?: { error: string; cause: string; fix: string }[];
  releaseInfo?: { released: string; source: string; notes: string };
};

// Source: https://github.com/Lightricks/ComfyUI-LTXVideo
// Official checkpoints go to: COMFYUI_ROOT/models/checkpoints/
export const MODELS: ModelVariant[] = [
  // ── v1.1 models (latest) ──────────────────────────────────────────────────
  {
    id: "ltx23-distilled-11",
    name: "LTX 2.3 Distilled 1.1",
    filename: "ltx-2.3-22b-distilled-1.1.safetensors",
    size: "46.1 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official v1.1 distilled model. 8 steps, CFG=1. Latest release from Lightricks. Requires sequential offloading on 32GB — file is 46GB.",
    badge: "v1.1 Latest",
    recommendation: "For 32GB VRAM: enable Sequential Offloading in ComfyUI settings (file is 46GB). For fastest inference, use the FP8 distilled variant instead.",
  },
  {
    id: "ltx23-distilled-11-fp8",
    name: "LTX 2.3 Distilled 1.1 FP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors",
    size: "25.2 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 quantized v1.1 distilled by Kijai. Best for 16GB VRAM. 8 steps, CFG=1.",
    badge: "16GB Best",
    recommendation: "Best choice for 16GB VRAM. Latest v1.1 FP8 distilled. Requires RTX 40xx+ for fp8 matmuls.",
    technicalNotes:
      "FP8 scaled quantization stores transformer weights as 8-bit floats with per-channel scaling tables alongside. On hardware with native FP8 matmul (RTX 40-series Ada, H100, RTX 50-series Blackwell), this gives near-BF16 quality at roughly half the VRAM and a meaningful speedup; on older GPUs the math falls back to a slow path and you should use the MXFP8 variant instead.\n\n'transformer_only' means this file contains only the DiT/transformer weights — not the VAE, not the text encoder. You will not be able to run a workflow with just this file; pair it with taeltx2_3.safetensors (VAE) and a Gemma 3 12B text encoder (FP4 mixed on 16 GB, FP8 scaled on 24 GB, BF16 on 32 GB+).\n\nDistilled v1.1 inference settings are 8 steps with CFG=1 — roughly 4× faster than running the dev model with the standard 30-step sampler. The v1.1 weights are noticeably better than v1.0 distilled for fast camera motion and character consistency.",
    whenToChoose:
      "Default choice for 16 GB cards (RTX 4070, 4070 Ti SUPER, 4080, 4070 Ti) and the fastest path on 24 GB (RTX 4090). You get the latest distilled quality at FP8 size, with hardware-accelerated matmul.\n\nPick the MXFP8 block-32 variant of the same file instead if you are on RTX 30-series — it stores the same weights in a format your GPU's tensor cores can handle without falling back to a slow emulation path.\n\nPick the BF16 transformer-only variant instead if you have 32 GB+ VRAM and want maximum quality, or if you plan to apply LoRAs that the FP8 path does not accept cleanly.",
    knownIssues: [
      {
        error: "RuntimeError: fp8 matmul not supported / 'unsupported dtype' on RTX 3090 / RTX 3060",
        cause: "RTX 30-series GPUs lack native FP8 tensor cores. The runtime cannot dispatch the FP8 path.",
        fix: "Switch to ltx-2.3-22b-distilled-1.1_transformer_only_mxfp8_block32.safetensors. Same weights, MXFP8 format runs on Ampere/Ada tensor cores. Same VRAM footprint.",
      },
      {
        error: "OOM at first inference on 16 GB even though file is only 25 GB",
        cause: "The full pipeline (transformer + Gemma text encoder + VAE + activations) exceeds 16 GB if you use the BF16 Gemma. Activations can spike to several GB at higher resolutions.",
        fix: "Use gemma_3_12B_it_fp4_mixed.safetensors as the text encoder. Enable model offload in ComfyUI's manager if you still OOM at 768p. Drop resolution to 576p as a last resort.",
      },
      {
        error: "First generation is very slow, later ones are fast",
        cause: "torch.compile warmup on first call. The model is being compiled for your specific GPU and input shape.",
        fix: "This is expected. Keep ComfyUI running and reuse the loaded model; subsequent generations skip compilation. If you change resolution or aspect, you'll get one more slow warmup.",
      },
      {
        error: "Workflow references '_transformer_only_fp8_scaled.safetensors' but file is named slightly differently",
        cause: "Older workflow JSONs reference the v1.0 filename (without '-1.1' in the name) — they need to be updated to use v1.1.",
        fix: "Open the workflow JSON in a text editor and replace the v1.0 filename string with 'ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors'. Or edit the Load node in ComfyUI and reselect the v1.1 file from the dropdown.",
      },
    ],
    releaseInfo: {
      released: "2026-04-13",
      source: "Kijai/LTX2.3_comfy (HuggingFace)",
      notes: "v1.1 release improved fast-motion stability and character consistency over v1.0.",
    },
  },
  {
    id: "ltx23-distilled-11-lora",
    name: "LTX 2.3 Distilled 1.1 LoRA (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_lora-dynamic_fro09_avg_rank_111_bf16.safetensors",
    size: "2.74 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Distilled LoRA v1.1 by Kijai. Use with the dev model for distilled-quality output on 16GB VRAM.",
    badge: "16GB LoRA",
    recommendation: "Pair with the dev FP8 model. Load as LoRA in ComfyUI models/loras/.",
  },
  {
    id: "ltx23-distilled-condsafe-lora",
    name: "LTX 2.3 Distilled 1.1 LoRA — fro90_ceil72 cond-safe (TenStrip)",
    filename: "ltx-2.3-22b-distilled-lora-1.1_fro90_ceil72_condsafe.safetensors",
    size: "662 MB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/TenStrip/LTX2.3_Distilled_Lora_1.1_Experiments",
    description: "Experimental community distilled LoRA v1.1 by TenStrip. The 'cond-safe' variant zeroes cross-attention bridges, adaln/scale-shift tables, gate logits, and prompt scale-shift — making it better suited for I2V and input-conditioned workflows than the standard dynamic LoRA. Place in models/loras/.",
    badge: "I2V LoRA",
    recommendation: "Pair with the dev FP8 model when running image-to-video or other input-conditioned workflows. Use the standard Kijai dynamic-rank LoRA for T2V instead.",
    isNew: true,
    technicalNotes:
      "This is one of TenStrip's experimental distillation LoRAs from the LTX2.3_Distilled_Lora_1.1_Experiments repo. 'fro90_ceil72' names the training schedule's hyperparameters (Frobenius norm target 0.90, ceiling 72). The decisive marker is the 'condsafe' suffix.\n\nIn the 'cond-safe' variant, the LoRA matrices for cross-attention bridges, adaLN scale/shift tables, gate logits, and prompt scale-shift are zeroed out. Why this matters: those are the exact paths that carry input-image conditioning in I2V workflows. The standard dynamic-rank distillation LoRA modifies them along with the rest of the network — which speeds up T2V but can subtly break I2V because the image features get routed differently than the base model expects.\n\n662 MB is small enough that you can keep this and the standard Kijai dynamic LoRA side-by-side and A/B test them per workflow. Place in ComfyUI/models/loras/ and select via the LoRA Loader node.",
    whenToChoose:
      "Use this LoRA when your workflow is image-to-video, first-frame conditioning, or any pipeline where preserving input-image fidelity matters more than maximum T2V quality. The cond-safe design specifically protects the conditioning paths that I2V relies on.\n\nFor pure text-to-video, the standard Kijai dynamic LoRA (ltx-2.3-22b-distilled-1.1_lora-dynamic_fro09_avg_rank_111_bf16.safetensors) is more proven and produces stronger motion. The cond-safe variant trades some T2V quality for I2V reliability.\n\nThis is an experimental release — try it against the standard LoRA on your own prompts before committing a production workflow to it.",
    knownIssues: [
      {
        error: "I2V output looks blurry or loses the input image's structure",
        cause: "LoRA is paired with the distilled base instead of the dev base. Distillation LoRAs are designed to convert the dev model into distilled-quality output — applying them on top of an already-distilled model double-distills and degrades quality.",
        fix: "Pair this LoRA with ltx-2.3-22b-dev-fp8.safetensors or the BF16 dev model, not the distilled FP8.",
      },
      {
        error: "No noticeable speedup vs running the dev model raw",
        cause: "Distillation LoRAs only give the 8-step speedup if you also configure the sampler for distilled inference.",
        fix: "Set sampler steps = 8 and CFG = 1 (matching the distilled model's inference profile). If you leave the sampler at the dev defaults (30 steps, CFG > 1), the LoRA does nothing useful.",
      },
      {
        error: "ComfyUI errors with 'LoRA shape mismatch' when loading",
        cause: "Loading the LoRA on top of a transformer whose weights have a different layout — typically a quantized variant whose internal layer naming was rewritten.",
        fix: "Apply this LoRA before quantization-aware loading, or use it with the BF16 dev base (ltx-2.3-22b-dev.safetensors) which has the canonical layer names.",
      },
    ],
    releaseInfo: {
      released: "2026-05-01",
      source: "TenStrip/LTX2.3_Distilled_Lora_1.1_Experiments (HuggingFace)",
      notes: "Experimental community release in the v1.1 distillation LoRA experiments repo. Also mirrored at SulphurAI/Sulphur-2-base/distill_loras/.",
    },
  },
  // ── v1.1 BF16 / MXFP8 (Kijai) ───────────────────────────────────────────
  {
    id: "ltx23-distilled-11-bf16",
    name: "LTX 2.3 Distilled 1.1 BF16 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 distilled 1.1 transformer-only by Kijai. For RTX 30xx or GPUs without FP8 support. Requires 48GB+ or sequential offloading on 32GB.",
    badge: "v1.1 BF16",
    recommendation: "Use when FP8 matmul (RTX 40xx+) is unavailable. 44GB — requires 48GB VRAM or sequential offloading on 32GB.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-11-mxfp8",
    name: "LTX 2.3 Distilled 1.1 MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 quantized distilled 1.1 by Kijai. Use on RTX 30xx GPUs that cannot run standard FP8 scaled matmul.",
    badge: "v1.1 MXFP8",
    recommendation: "RTX 30xx workaround — use this when your GPU lacks RTX 40xx-style FP8 matmul support. Same VRAM as fp8_scaled.",
    isNew: true,
  },
  // ── v1.0 models (previous) ────────────────────────────────────────────────
  {
    id: "ltx23-dev",
    name: "LTX 2.3 Dev",
    filename: "ltx-2.3-22b-dev.safetensors",
    size: "~42 GB",
    vram: 32,
    type: "full",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Full BF16 dev model. Flexible and trainable. 42GB — requires 48GB VRAM or sequential offloading on 32GB.",
    badge: "Official",
    recommendation: "Best for LoRA training and fine-tuning. 42GB — enable Sequential Offloading on 32GB cards.",
    technicalNotes:
      "ltx-2.3-22b-dev.safetensors is the full-precision (BF16) base model from Lightricks — the source weights that every FP8, MXFP8, NVFP4, and distilled variant is derived from. 22B parameters at BF16 means ~42 GB on disk. This is the file you train against, not the file you reach for to make a quick clip.\n\nUnlike the distilled checkpoints, the dev model uses the full 30-step diffusion schedule with CFG > 1, accepts negative prompts meaningfully, and produces noticeably different output when you stack multiple LoRAs. The trade-off is roughly 4× slower inference and a much larger VRAM footprint.\n\nOn 32 GB cards (RTX 5090, A6000) you can run inference with ComfyUI's Sequential Offloading enabled — the model streams layers to and from GPU memory during the forward pass. This is slow but works. For comfortable inference you want 48 GB+ (A6000 Ada, H100 PCIe).",
    whenToChoose:
      "Pick the dev BF16 model when you are training LoRAs or fine-tuning — quantized checkpoints lose the gradient precision you need. Also pick it when you need maximum fidelity for a hero shot and inference time is not the constraint.\n\nFor day-to-day generation, ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors or ltx-2.3-22b-dev-fp8.safetensors are better defaults — they cut VRAM in half and inference time by ~4×, with a quality delta most users cannot see.\n\nFor LoRA training specifically, this file is non-negotiable. The official LoRA training scripts (and community trainers like ai-toolkit) expect BF16 source weights to compute meaningful gradients.",
    knownIssues: [
      {
        error: "Loaded the model but OOM on first inference on a 32 GB card",
        cause: "Activations + text encoder + VAE exceed remaining VRAM after the 42 GB transformer is loaded. Even with offloading enabled, peak memory during attention can spike.",
        fix: "Enable Sequential Offloading in ComfyUI settings (not just Model Offload). Also drop to the FP4 Gemma text encoder (gemma_3_12B_it_fp4_mixed.safetensors). Reduce resolution to 576p as a fallback. For comfortable inference at 768p or 1024p you need 48 GB+ VRAM.",
      },
      {
        error: "Download is extremely slow over residential connection",
        cause: "42 GB file served via HuggingFace's xet protocol. Browser downloads max out at one TCP stream.",
        fix: "Use `huggingface-cli download Lightricks/LTX-2.3 ltx-2.3-22b-dev.safetensors --local-dir .` for multi-stream parallel chunks. Or use aria2c with -x 8. Plan for the size — at 100 Mbps this is ~1 hour.",
      },
      {
        error: "Training script crashes on backward pass with 'mixed precision' error",
        cause: "Loading the BF16 weights in FP16 mixed precision causes overflow in attention.",
        fix: "Use BF16 mixed precision, not FP16, in your training config. PyTorch's autocast(dtype=torch.bfloat16) is the standard setting for LTX training.",
      },
    ],
    releaseInfo: {
      released: "2026-03-04",
      source: "Lightricks/LTX-2.3 (HuggingFace)",
      notes: "Initial LTX 2.3 release. v1.1 weights live in the same repo as ltx-2.3-22b-distilled-1.1.safetensors.",
    },
  },
  {
    id: "ltx23-distilled",
    name: "LTX 2.3 Distilled",
    filename: "ltx-2.3-22b-distilled.safetensors",
    size: "~42 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "v1.0 distilled version. 8 steps, CFG=1. Superseded by v1.1.",
    recommendation: "Previous version. Use v1.1 Distilled for latest quality.",
  },
  {
    id: "ltx23-distilled-fp8",
    name: "LTX 2.3 Distilled FP8 v3 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v3.safetensors",
    size: "25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v3 by Kijai. Previous version, superseded by v1.1 FP8.",
    recommendation: "Previous version. Use v1.1 FP8 for latest quality.",
  },
  {
    id: "ltx23-dev-fp8",
    name: "LTX 2.3 Dev FP8 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_fp8_input_scaled.safetensors",
    size: "25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 quantized dev model by Kijai. Runs on 16GB VRAM. Supports LoRA. Place in models/checkpoints/.",
    badge: "16GB LoRA",
    recommendation: "Use this (not distilled) if you want to apply LoRA weights on 16GB VRAM.",
  },
  {
    id: "ltx23-distilled-fp8-24gb",
    name: "LTX 2.3 Distilled 1.1 (bf16, 24GB)",
    filename: "ltx-2.3-22b-distilled-1.1.safetensors",
    size: "46.1 GB",
    vram: 24,
    vramMax: 31,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official v1.1 distilled model runnable on 24GB with sequential offloading enabled in ComfyUI.",
    badge: "24GB",
    recommendation: "Enable sequential offloading in ComfyUI settings. Uses latest v1.1 official weights.",
  },
  // ── Dev model additional variants (Kijai) ─────────────────────────────────
  {
    id: "ltx23-dev-bf16",
    name: "LTX 2.3 Dev BF16 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "full",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 dev transformer-only by Kijai. 44GB — requires 48GB VRAM or sequential offloading on 32GB. Place in models/checkpoints/.",
    badge: "Dev BF16",
    recommendation: "Use when training LoRA with full BF16 precision. 44GB — enable Sequential Offloading on 32GB cards.",
    isNew: false,
  },
  {
    id: "ltx23-dev-fp8-scaled",
    name: "LTX 2.3 Dev FP8 Scaled (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_fp8_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 scaled dev model by Kijai. 16GB VRAM. Supports LoRA. Place in models/checkpoints/.",
    badge: "Dev FP8",
    recommendation: "Alternative FP8 quantization for dev. Use when fp8_input_scaled has compatibility issues.",
    isNew: false,
  },
  {
    id: "ltx23-dev-mxfp8",
    name: "LTX 2.3 Dev MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 dev model by Kijai. 16GB VRAM. Supports LoRA. Use on RTX 30xx GPUs that cannot run standard FP8 scaled. Place in models/checkpoints/.",
    badge: "Dev MXFP8",
    recommendation: "RTX 30xx workaround for dev/quality path — use when standard FP8 matmul is unsupported. Supports LoRA.",
    isNew: false,
  },
  // ── Distilled v1.0 additional variants (Kijai) ────────────────────────────
  {
    id: "ltx23-distilled-bf16",
    name: "LTX 2.3 Distilled BF16 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 distilled v1.0 transformer-only by Kijai. 44GB — requires 48GB VRAM or sequential offloading on 32GB.",
    recommendation: "Previous v1.0 BF16 distilled. Use v1.1 BF16 for latest quality. Enable Sequential Offloading on 32GB.",
    isNew: false,
  },
  {
    id: "ltx23-distilled-fp8-v1",
    name: "LTX 2.3 Distilled FP8 v1 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v1 by Kijai. Earliest FP8 release, superseded by v3.",
    recommendation: "Previous version. Use FP8 v3 or v1.1 FP8 for better quality.",
    isNew: false,
  },
  {
    id: "ltx23-distilled-fp8-v2",
    name: "LTX 2.3 Distilled FP8 v2 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v2.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v2 by Kijai. Superseded by v3.",
    recommendation: "Previous version. Use FP8 v3 or v1.1 FP8 for better quality.",
    isNew: false,
  },
  {
    id: "ltx23-distilled-fp8-scaled",
    name: "LTX 2.3 Distilled FP8 Scaled (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 scaled distilled by Kijai. Alternative FP8 quantization method.",
    recommendation: "Alternative FP8 quantization. Use v1.1 FP8 for latest quality.",
    isNew: false,
  },
  {
    id: "ltx23-distilled-mxfp8",
    name: "LTX 2.3 Distilled MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 distilled v1.0 by Kijai. RTX 30xx workaround — use when standard FP8 scaled is unsupported.",
    recommendation: "Previous v1.0 MXFP8 (RTX 30xx). Use v1.1 MXFP8 for latest quality.",
    isNew: false,
  },
  // ── Official FP8 models (Lightricks) ─────────────────────────────────────
  {
    id: "ltx23-dev-fp8-official",
    name: "LTX 2.3 Dev FP8 (Official)",
    filename: "ltx-2.3-22b-dev-fp8.safetensors",
    size: "29.1 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-fp8",
    description: "Official FP8 dev model from Lightricks. 29.1GB, runs on 16GB VRAM.",
    badge: "Official FP8",
    recommendation: "Official FP8 from Lightricks. Alternative to Kijai's FP8 dev model.",
    isNew: false,
    technicalNotes:
      "This is Lightricks' first-party FP8 quantization of the LTX 2.3 dev base model. Unlike Kijai's transformer-only variants, the official file is a complete checkpoint — it includes the full set of submodules needed to run inference, which is why it weighs ~29 GB compared to ~25 GB for transformer-only quants.\n\n'Dev' means this is the non-distilled base model. It runs at full 30-step sampling with CFG > 1, which is slower than the 8-step distilled path but more flexible: it accepts LoRAs cleanly, responds to negative prompts, and is the right base for fine-tuning experiments.\n\nFP8 hardware is required (RTX 40-series Ada or newer, H100, Blackwell). On Ampere or older you'll either crash or fall back to a slow emulation path — switch to the BF16 dev file in that case.",
    whenToChoose:
      "Use this when you specifically want official Lightricks FP8 weights — for example, you're building a service that needs first-party-signed weights, or you're matching the exact reference output documented in Lightricks' release notes.\n\nFor most users, ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors is the better default — it's smaller, newer (v1.1), faster (8 steps), and from the community-trusted Kijai mirror that all current ComfyUI workflows reference. The official dev FP8 is what you reach for when you need LoRA support at FP8 size and the distilled path doesn't fit your use case.",
    knownIssues: [
      {
        error: "Workflow expects a 'transformer_only' filename but I downloaded the full checkpoint",
        cause: "Most published ComfyUI workflows are written against Kijai's transformer_only files, not Lightricks' full checkpoints.",
        fix: "Either rewire the workflow's LoadCheckpoint to point at this file (instead of separate transformer + VAE + text encoder loads), or switch to ltx-2.3-22b-dev_transformer_only_fp8_scaled.safetensors from Kijai.",
      },
      {
        error: "Generation looks correct but is slower than expected on a 4090",
        cause: "This is the dev model, not distilled. It runs at 30 steps by default vs the distilled model's 8 steps.",
        fix: "Either accept the speed for higher fidelity, or switch to ltx-2.3-22b-distilled-fp8.safetensors (also official, distilled) and use 8 steps with CFG=1.",
      },
    ],
    releaseInfo: {
      released: "2026-03-16",
      source: "Lightricks/LTX-2.3-fp8 (HuggingFace)",
      notes: "Official first-party FP8 release from Lightricks, posted shortly after the initial LTX 2.3 launch.",
    },
  },
  {
    id: "ltx23-distilled-fp8-official",
    name: "LTX 2.3 Distilled FP8 (Official)",
    filename: "ltx-2.3-22b-distilled-fp8.safetensors",
    size: "29.5 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-fp8",
    description: "Official FP8 distilled model from Lightricks. 8 steps, CFG=1.",
    badge: "Official FP8",
    recommendation: "Official FP8 distilled from Lightricks. Alternative to Kijai's FP8.",
    isNew: false,
    technicalNotes:
      "Lightricks' first-party FP8 quantization of the v1.0 distilled model. Like the official dev FP8, this is a full checkpoint — transformer + VAE + text encoder integration glue — which is why the file is ~29.5 GB versus ~25 GB for a transformer-only quant.\n\nThe weights here are the v1.0 distilled checkpoint quantized to FP8. That means 8-step sampling with CFG=1, fast inference, and the v1.0 quality profile — not the v1.1 improvements that landed later in April 2026.\n\nFP8 hardware (RTX 40-series Ada or newer) is required. On RTX 30-series the matmul falls back to a slow path; switch to the MXFP8 block-32 variant from Kijai if that's your GPU.",
    whenToChoose:
      "Use this when you need official Lightricks distilled weights at FP8 size — for example, building a reproducible reference pipeline or matching the exact outputs documented in Lightricks' v1.0 distilled release notes.\n\nFor most ComfyUI users, ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors (Kijai, v1.1) is a better default: newer weights, smaller file, and the filename every current workflow JSON references.\n\nIf you need v1.0 specifically (for reproducibility or comparison), this is the cleanest source — official, signed, in the same repo as the official dev FP8.",
    knownIssues: [
      {
        error: "Output quality is lower than the Kijai v1.1 FP8 file at the same settings",
        cause: "This file is v1.0 weights, not v1.1. v1.1 is a meaningfully better release for fast motion and consistency.",
        fix: "Switch to ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors if you don't need v1.0 specifically for reproducibility.",
      },
      {
        error: "Workflow expects a 'transformer_only' file but downloaded this full checkpoint",
        cause: "Most community workflow JSONs load the transformer, VAE, and text encoder separately and expect Kijai-style transformer-only files.",
        fix: "Either rewire the workflow to load the full checkpoint (single LoadCheckpoint node), or download ltx-2.3-22b-distilled_transformer_only_fp8_scaled.safetensors from Kijai for the v1.0 transformer-only equivalent.",
      },
      {
        error: "Generation is slower than expected even on a 4090",
        cause: "Activations + Gemma BF16 text encoder + VAE add up. The 29.5 GB on-disk size grows substantially during inference.",
        fix: "Use gemma_3_12B_it_fp4_mixed.safetensors as the text encoder. Cap resolution at 768p on 16 GB cards. On 24 GB you can run 1024p comfortably.",
      },
    ],
    releaseInfo: {
      released: "2026-03-16",
      source: "Lightricks/LTX-2.3-fp8 (HuggingFace)",
      notes: "First-party FP8 distilled release. Same v1.0 weights as the non-FP8 distilled, quantized to FP8. Lightricks did not publish a v1.1 FP8 in this repo — use the Kijai mirror for v1.1.",
    },
  },
  // ── LoRA v1.1 ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-distilled-lora-384-11",
    name: "LTX 2.3 Distilled LoRA 384 v1.1 (Official)",
    filename: "ltx-2.3-22b-distilled-lora-384-1.1.safetensors",
    size: "7.61 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official distilled LoRA rank-384 v1.1. Use with dev model. Place in models/loras/.",
    badge: "v1.1 LoRA",
    recommendation: "Latest official LoRA. Pair with dev model for distilled-quality output.",
    isNew: false,
  },
  // ── LoRA v1.0 ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-distilled-lora-384",
    name: "LTX 2.3 Distilled LoRA 384 (Official)",
    filename: "ltx-2.3-22b-distilled-lora-384.safetensors",
    size: "~7.6 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official distilled LoRA rank-384 v1.0. Pair with dev model. Place in models/loras/.",
    badge: "v1.0 LoRA",
    recommendation: "Previous v1.0 LoRA. Use v1.1 LoRA for latest quality.",
    isNew: false,
    technicalNotes:
      "ltx-2.3-22b-distilled-lora-384.safetensors is the official Lightricks distillation LoRA at rank 384 — the v1.0 release that shipped with the initial LTX 2.3 launch. Applying it on top of the dev model gives output equivalent to the distilled checkpoint: 8-step sampling with CFG=1 at distilled quality.\n\nRank 384 is comparatively high — high enough to capture most of the distillation behavior end-to-end without the parameter savings you'd see from a low-rank LoRA. The file is ~7.6 GB on disk, which is large for a LoRA but tiny next to the 42 GB base model it stacks on top of.\n\nThe rank-384 design lets Lightricks ship distillation as a swappable behavior change rather than a separate checkpoint — useful for training experiments where you want to compare dev + distill-LoRA against the standalone distilled model.",
    whenToChoose:
      "For most users, switch to ltx-2.3-22b-distilled-lora-384-1.1.safetensors — the v1.1 release of the same LoRA. v1.1 has measurable improvements in fast-motion stability and prompt adherence over v1.0, with identical file structure.\n\nThis v1.0 file is worth keeping when you need to reproduce results from older workflow JSONs that pin the v1.0 filename, or when you're A/B testing v1.0 vs v1.1 to evaluate the upgrade.\n\nFor 16 GB inference where memory matters more than reproducibility, the Kijai dynamic LoRA (ltx-2.3-22b-distilled-1.1_lora-dynamic_fro09_avg_rank_111_bf16.safetensors) is ~3× smaller and loads faster.",
    knownIssues: [
      {
        error: "LoRA loads but generation looks identical to base model — no distillation happening",
        cause: "Sampler is still configured for the dev model (30 steps, CFG > 1). Distillation LoRAs only show their effect with distilled sampling settings.",
        fix: "Set sampler steps = 8 and CFG = 1 in the KSampler node. The LoRA's job is to make the dev model behave like the distilled model — it can't change the number of denoising steps for you.",
      },
      {
        error: "Stacked this LoRA with the Kijai dynamic LoRA and got garbage output",
        cause: "Both LoRAs cover the same task — converting dev behavior to distilled behavior. Stacking them double-applies the distillation and overshoots.",
        fix: "Use exactly one distillation LoRA at a time. If you want to compose with content/style LoRAs, apply the distillation LoRA at full strength and other LoRAs at their normal weights.",
      },
      {
        error: "Workflow expects the v1.1 file, but only the v1.0 is in models/loras/",
        cause: "Workflow JSONs are filename-specific. v1.0 and v1.1 are not interchangeable by string.",
        fix: "Either download ltx-2.3-22b-distilled-lora-384-1.1.safetensors (recommended), or edit the workflow's LoRA Loader node to point at the v1.0 file you have.",
      },
    ],
    releaseInfo: {
      released: "2026-03-04",
      source: "Lightricks/LTX-2.3 (HuggingFace)",
      notes: "Initial v1.0 distillation LoRA. Superseded by ltx-2.3-22b-distilled-lora-384-1.1.safetensors in the v1.1 release on 2026-04-13.",
    },
  },
  {
    id: "ltx23-distilled-lora-dynamic",
    name: "LTX 2.3 Distilled LoRA Dynamic r105 (Kijai)",
    filename: "ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors",
    size: "~2.5 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Dynamic rank LoRA (avg rank 105) by Kijai. Pair with dev model. Place in models/loras/.",
    badge: "Dynamic LoRA",
    recommendation: "v1.0 dynamic LoRA. Use v1.1 dynamic LoRA (rank 111) for latest quality.",
    isNew: false,
  },
  // ── Upscalers ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-spatial-upscaler-x15",
    name: "Spatial Upscaler x1.5",
    filename: "ltx-2.3-spatial-upscaler-x1.5-1.0.safetensors",
    size: "1.09 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Spatial upscaler x1.5 for two-stage pipelines. Place in models/latent_upscale_models/.",
    recommendation: "Use when x2 upscale is too aggressive. Gentler upscaling option.",
    isNew: false,
  },
  {
    id: "ltx23-temporal-upscaler",
    name: "Temporal Upscaler x2",
    filename: "ltx-2.3-temporal-upscaler-x2-1.0.safetensors",
    size: "262 MB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Temporal upscaler x2 for frame interpolation. Place in models/latent_upscale_models/.",
    recommendation: "Optional. Use to double frame count (e.g. 65→129 frames) for smoother motion.",
    isNew: false,
  },
  {
    id: "ltx23-spatial-upscaler-x2-11",
    name: "Spatial Upscaler x2 v1.1",
    filename: "ltx-2.3-spatial-upscaler-x2-1.1.safetensors",
    size: "~1 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Updated spatial upscaler x2 v1.1. Place in models/latent_upscale_models/.",
    badge: "v1.1",
    recommendation: "Updated upscaler. Prefer over v1.0 for better upscaling quality.",
    isNew: false,
  },
  // ── required for all setups ───────────────────────────────────────────────
  {
    id: "ltx23-spatial-upscaler",
    name: "Spatial Upscaler x2",
    filename: "ltx-2.3-spatial-upscaler-x2-1.0.safetensors",
    size: "~1 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Spatial upscaler x2 for two-stage pipelines. Place in models/latent_upscale_models/.",
    recommendation: "Optional. Use in a two-stage pipeline to upscale output resolution after generation.",
  },
  {
    id: "ltx23-vae",
    name: "LTX 2.3 VAE",
    filename: "taeltx2_3.safetensors",
    size: "~0.5 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy/blob/main/vae/taeltx2_3.safetensors",
    description: "VAE by Kijai. Required for all ComfyUI workflows. Place in models/vae/.",
    badge: "Required",
    recommendation: "Required for all setups. Download this first regardless of your VRAM.",
    technicalNotes:
      "taeltx2_3.safetensors is the Tiny AutoEncoder (TAE) for LTX 2.3 — a distilled, much smaller replacement for the original full VAE. The 'tae' prefix marks it as a tiny encoder/decoder pair shipped specifically for ComfyUI's pipeline; the file is around half a gigabyte versus several gigabytes for a full VAE.\n\nEvery LTX 2.3 ComfyUI workflow — T2V, I2V, two-stage, IC-LoRA — references this exact filename in its LoadVAE / VAELoader node. The string is hardcoded in published workflow JSONs, so the filename matters: do not rename, do not substitute, and do not move it out of models/vae/.\n\nThe TAE handles both the encoder (image → latents for I2V) and the decoder (latents → frames at the end of inference). Quality-wise it is calibrated against the full VAE so artifacts are minimal, but if you see banding or color drift on long clips, the standalone BF16 video VAE is the heavier alternative.",
    whenToChoose:
      "This is not an alternative — it is required. Every workflow on this site, every ComfyUI workflow shipped by Lightricks or the community, and every IC-LoRA pipeline loads taeltx2_3.safetensors. Download it first regardless of which transformer/quant you pick.\n\nThe one case where you would use something else is if a workflow explicitly references LTX23_video_vae_bf16.safetensors — that is the BF16 standalone video VAE, used by a small number of two-stage or HDR workflows that need the heavier decoder.",
    knownIssues: [
      {
        error: "VAELoader: file not found / 'taeltx2_3.safetensors not in list'",
        cause: "File placed in ComfyUI/models/ root, or in checkpoints/ instead of vae/.",
        fix: "Move the file to ComfyUI/models/vae/taeltx2_3.safetensors. Click the refresh button on the VAELoader node so ComfyUI re-scans the directory.",
      },
      {
        error: "VAE decoded image is solid green / black / corrupt",
        cause: "Partial download — HF's xet protocol can leave a truncated file on flaky connections that still looks like a valid .safetensors header.",
        fix: "Delete the file and redownload. If you used a browser, switch to `huggingface-cli download` or `aria2c` with retry. Verify by checking file size matches HuggingFace's reported size (~500 MB).",
      },
      {
        error: "Workflow loads but VAE node is red after rename",
        cause: "The filename is hardcoded in workflow JSONs as taeltx2_3.safetensors.",
        fix: "Rename it back. If you have other VAE files in the directory, keep taeltx2_3.safetensors and let the others coexist.",
      },
    ],
    releaseInfo: {
      released: "2026-03",
      source: "Kijai/LTX2.3_comfy (HuggingFace)",
      notes: "Shipped alongside Kijai's initial LTX 2.3 ComfyUI port in March 2026.",
    },
  },
  // ── Audio / Video VAE & Text Encoder components (Kijai) ──────────────────
  {
    id: "ltx23-audio-vae",
    name: "LTX 2.3 Audio VAE (Kijai)",
    filename: "LTX23_audio_vae_bf16.safetensors",
    size: "~1 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Audio VAE for audio-conditioned video generation. Place in models/vae/. Enables audio-to-video workflows.",
    badge: "New: Audio",
    recommendation: "Required for audio-conditioned workflows. Unlocks new audio-to-video capability.",
    isNew: true,
  },
  {
    id: "ltx23-video-vae",
    name: "LTX 2.3 Video VAE (Kijai)",
    filename: "LTX23_video_vae_bf16.safetensors",
    size: "~1 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Standalone video VAE BF16 by Kijai. Alternative to taeltx2_3. Place in models/vae/.",
    recommendation: "Alternative VAE option. Use in workflows that require the separate BF16 VAE component.",
    isNew: false,
  },
  {
    id: "ltx23-text-projection",
    name: "LTX 2.3 Text Projection (Kijai)",
    filename: "ltx-2.3_text_projection_bf16.safetensors",
    size: "~0.5 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Text projection BF16 component by Kijai. Place in models/text_encoders/.",
    recommendation: "Required for workflows using separate text encoder components.",
    isNew: false,
  },
  // ── 2026-05 additions: IC-LoRAs, NVFP4, Gemma 3 text encoder ─────────────
  {
    id: "ltx23-ic-lora-union",
    name: "IC-LoRA Union Control",
    filename: "ltx-2.3-22b-ic-lora-union-control-ref0.5.safetensors",
    size: "654 MB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-22b-IC-LoRA-Union-Control",
    description: "Unified Canny + Depth control IC-LoRA. One LoRA covering edge and depth conditioning. Place in models/loras/.",
    badge: "IC-LoRA Union",
    recommendation: "Use the official IC-LoRA ComfyUI workflow with LTXICLoRALoaderModelOnly + LTXAddVideoICLoRAGuide (Reference Downscale Factor 0.5).",
    isNew: true,
  },
  {
    id: "ltx23-ic-lora-motion-track",
    name: "IC-LoRA Motion Track Control",
    filename: "ltx-2.3-22b-ic-lora-motion-track-control-ref0.5.safetensors",
    size: "327 MB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-22b-IC-LoRA-Motion-Track-Control",
    description: "Motion-track IC-LoRA. Drive motion with sparse point trajectories (SpatialTrackerV2 or hand-drawn). Place in models/loras/.",
    badge: "IC-LoRA Motion",
    recommendation: "For V2V motion transfer. Pair with the official IC-LoRA workflow at Reference Downscale Factor 0.5.",
    isNew: true,
  },
  {
    id: "ltx23-ic-lora-hdr",
    name: "IC-LoRA HDR",
    filename: "ltx-2.3-22b-ic-lora-hdr-0.9.safetensors",
    size: "327 MB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-22b-IC-LoRA-HDR",
    description: "16-bit HDR generation IC-LoRA. SDR→HDR via LogC3 transform. Place in models/loras/.",
    badge: "IC-LoRA HDR",
    recommendation: "Required: also download the HDR scene-emb file. Enables HDR text/image-to-video and SDR-to-HDR conversion.",
    isNew: true,
  },
  {
    id: "ltx23-ic-lora-hdr-emb",
    name: "IC-LoRA HDR Scene Embeddings",
    filename: "ltx-2.3-22b-ic-lora-hdr-scene-emb.safetensors",
    size: "12.6 MB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-22b-IC-LoRA-HDR",
    description: "Companion scene-embeddings file for the HDR IC-LoRA. Place in models/loras/.",
    recommendation: "Required when using the HDR IC-LoRA.",
    isNew: true,
  },
  {
    id: "ltx23-ic-lora-lipdub",
    name: "IC-LoRA LipDub",
    filename: "ltx-2.3-22b-ic-lora-lipdub-0.9.safetensors",
    size: "2.47 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-22b-IC-LoRA-LipDub",
    description: "Lip-dubbing IC-LoRA based on JustDubIt research. Joint audio-visual diffusion for dubbing. Place in models/loras/.",
    badge: "IC-LoRA LipDub",
    recommendation: "Use for video lip-sync / dubbing. Pair with the audio VAE.",
    isNew: true,
  },
  {
    id: "ltx23-dev-nvfp4",
    name: "LTX 2.3 Dev NVFP4 (Official)",
    filename: "ltx-2.3-22b-dev-nvfp4.safetensors",
    size: "21.7 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-nvfp4",
    description: "NVFP4 quantized dev model. Native nvfp4 matmul on Blackwell GPUs (RTX 50xx). 21.7GB.",
    badge: "NVFP4 (Blackwell)",
    recommendation: "Best size/quality tradeoff on RTX 50xx. On older GPUs it falls back to slow paths — prefer FP8 there.",
    isNew: true,
  },
  {
    id: "ltx23-gemma-fp4",
    name: "Gemma 3 12B IT FP4 Mixed (Text Encoder)",
    filename: "gemma_3_12B_it_fp4_mixed.safetensors",
    size: "9.5 GB",
    vram: 8,
    type: "lora",
    hfUrl: "https://huggingface.co/Comfy-Org/ltx-2",
    description: "FP4-mixed Gemma 3 12B IT text encoder (~90% FP4 layers). Required for 16-24 GB ComfyUI workflows. Place in models/text_encoders/.",
    badge: "Required (16/24 GB)",
    recommendation: "Use this on 16/24 GB VRAM cards. Full BF16 Gemma OOMs alongside the transformer.",
    isNew: true,
  },
  {
    id: "ltx23-gemma-fp8",
    name: "Gemma 3 12B IT FP8 Scaled (Text Encoder)",
    filename: "gemma_3_12B_it_fp8_scaled.safetensors",
    size: "13.2 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Comfy-Org/ltx-2",
    description: "FP8-scaled Gemma 3 12B IT text encoder. Alternative to FP4 with marginally higher precision. Place in models/text_encoders/.",
    recommendation: "Alternative for 16-24 GB cards. Slightly higher quality than FP4 at 3.7 GB more.",
    isNew: true,
  },
  {
    id: "ltx23-gemma-full",
    name: "Gemma 3 12B IT BF16 (Text Encoder)",
    filename: "comfy_gemma_3_12B_it.safetensors",
    size: "24.4 GB",
    vram: 32,
    type: "lora",
    hfUrl: "https://huggingface.co/Comfy-Org/ltx-2",
    description: "Full BF16 Gemma 3 12B IT text encoder (HF filename gemma_3_12B_it.safetensors — workflows reference it as comfy_gemma_3_12B_it.safetensors, rename after download). Place in models/text_encoders/.",
    badge: "Required (32 GB+)",
    recommendation: "Rename to comfy_gemma_3_12B_it.safetensors after downloading. Use on 32 GB+ cards for highest text-encoder quality.",
    isNew: true,
  },
  {
    id: "ltx23-dev-fp8-dash",
    name: "LTX 2.3 Dev FP8 Input Scaled (dash filename, Kijai)",
    filename: "ltx-2-3-22b-dev_transformer_only_fp8_input_scaled.safetensors",
    size: "25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 input-scaled dev model under the alternate `ltx-2-3-…` (dash) filename. Same weights, different name.",
    recommendation: "Prefer the dotted-filename version unless a specific workflow references this exact name.",
    isNew: false,
  },
];

export function getModelsForVram(vram: number): ModelVariant[] {
  return MODELS.filter((m) => m.vram <= vram && (m.vramMax === undefined || vram <= m.vramMax));
}
