export type ModelVariant = {
  id: string;
  name: string;
  filename: string;
  size: string;
  vram: number;
  vramMax?: number;
  type: "full" | "distilled" | "fp8" | "lora";
  hfUrl: string;
  description: string;
  badge?: string;
  recommendation?: string;
  isNew?: boolean;
};

// Source: https://github.com/Lightricks/ComfyUI-LTXVideo
// Official checkpoints go to: COMFYUI_ROOT/models/checkpoints/
export const MODELS: ModelVariant[] = [
  // ── v1.1 models (latest) ──────────────────────────────────────────────────
  {
    id: "ltx23-distilled-11",
    name: "LTX 2.3 Distilled 1.1",
    filename: "ltx-2.3-22b-distilled-1.1.safetensors",
    size: "46.1 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official v1.1 distilled model. 8 steps, CFG=1. Latest release from Lightricks.",
    badge: "v1.1 Latest",
    recommendation: "Recommended for 32GB VRAM. Newest official distilled checkpoint.",
  },
  {
    id: "ltx23-distilled-11-fp8",
    name: "LTX 2.3 Distilled 1.1 FP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors",
    size: "25.2 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 quantized v1.1 distilled by Kijai. Best for 16GB VRAM. 8 steps, CFG=1.",
    badge: "16GB Best",
    recommendation: "Best choice for 16GB VRAM. Latest v1.1 FP8 distilled. Requires RTX 40xx+ for fp8 matmuls.",
  },
  {
    id: "ltx23-distilled-11-lora",
    name: "LTX 2.3 Distilled 1.1 LoRA (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_lora-dynamic_fro09_avg_rank_111_bf16.safetensors",
    size: "2.74 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Distilled LoRA v1.1 by Kijai. Use with the dev model for distilled-quality output on 16GB VRAM.",
    badge: "16GB LoRA",
    recommendation: "Pair with the dev FP8 model. Load as LoRA in ComfyUI models/loras/.",
  },
  // ── v1.1 BF16 / MXFP8 (Kijai) ───────────────────────────────────────────
  {
    id: "ltx23-distilled-11-bf16",
    name: "LTX 2.3 Distilled 1.1 BF16 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 distilled 1.1 transformer-only by Kijai. For GPUs without FP8 support (pre-RTX 40xx).",
    badge: "v1.1 BF16",
    recommendation: "Use when FP8 hardware (RTX 40xx+) is unavailable. Full BF16 precision on 32GB VRAM.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-11-mxfp8",
    name: "LTX 2.3 Distilled 1.1 MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled-1.1_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 quantized distilled 1.1 by Kijai. Alternative FP8 format for RTX 40xx+.",
    badge: "v1.1 MXFP8",
    recommendation: "Block-32 MXFP8 quantization. Alternative to standard FP8 scaled for 16GB VRAM.",
    isNew: true,
  },
  // ── v1.0 models (previous) ────────────────────────────────────────────────
  {
    id: "ltx23-dev",
    name: "LTX 2.3 Dev",
    filename: "ltx-2.3-22b-dev.safetensors",
    size: "~42 GB",
    vram: 32,
    type: "full",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Full dev model. Flexible and trainable. Recommended 32GB+ VRAM.",
    badge: "Official",
    recommendation: "Best for LoRA training and fine-tuning. Supports CFG guidance.",
  },
  {
    id: "ltx23-distilled",
    name: "LTX 2.3 Distilled",
    filename: "ltx-2.3-22b-distilled.safetensors",
    size: "~42 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "v1.0 distilled version. 8 steps, CFG=1. Superseded by v1.1.",
    recommendation: "Previous version. Use v1.1 Distilled for latest quality.",
  },
  {
    id: "ltx23-distilled-fp8",
    name: "LTX 2.3 Distilled FP8 v3 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v3.safetensors",
    size: "25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v3 by Kijai. Previous version, superseded by v1.1 FP8.",
    recommendation: "Previous version. Use v1.1 FP8 for latest quality.",
  },
  {
    id: "ltx23-dev-fp8",
    name: "LTX 2.3 Dev FP8 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_fp8_input_scaled.safetensors",
    size: "25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 quantized dev model by Kijai. Runs on 16GB VRAM. Supports LoRA. Place in models/checkpoints/.",
    badge: "16GB LoRA",
    recommendation: "Use this (not distilled) if you want to apply LoRA weights on 16GB VRAM.",
  },
  {
    id: "ltx23-distilled-fp8-24gb",
    name: "LTX 2.3 Distilled 1.1 (bf16, 24GB)",
    filename: "ltx-2.3-22b-distilled-1.1.safetensors",
    size: "46.1 GB",
    vram: 24,
    vramMax: 31,
    type: "distilled",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official v1.1 distilled model runnable on 24GB with sequential offloading enabled in ComfyUI.",
    badge: "24GB",
    recommendation: "Enable sequential offloading in ComfyUI settings. Uses latest v1.1 official weights.",
  },
  // ── Dev model additional variants (Kijai) ─────────────────────────────────
  {
    id: "ltx23-dev-bf16",
    name: "LTX 2.3 Dev BF16 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "full",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 dev transformer-only by Kijai. Full precision for 32GB VRAM. Place in models/checkpoints/.",
    badge: "Dev BF16",
    recommendation: "Transformer-only BF16 dev model. Use when training LoRA with full BF16 precision.",
    isNew: true,
  },
  {
    id: "ltx23-dev-fp8-scaled",
    name: "LTX 2.3 Dev FP8 Scaled (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_fp8_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 scaled dev model by Kijai. 16GB VRAM. Supports LoRA. Place in models/checkpoints/.",
    badge: "Dev FP8",
    recommendation: "Alternative FP8 quantization for dev. Use when fp8_input_scaled has compatibility issues.",
    isNew: true,
  },
  {
    id: "ltx23-dev-mxfp8",
    name: "LTX 2.3 Dev MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-dev_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 dev model by Kijai. 16GB VRAM. Supports LoRA. Place in models/checkpoints/.",
    badge: "Dev MXFP8",
    recommendation: "MXFP8 dev model for 16GB VRAM. Requires RTX 40xx+.",
    isNew: true,
  },
  // ── Distilled v1.0 additional variants (Kijai) ────────────────────────────
  {
    id: "ltx23-distilled-bf16",
    name: "LTX 2.3 Distilled BF16 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_bf16.safetensors",
    size: "~44 GB",
    vram: 32,
    type: "distilled",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "BF16 distilled v1.0 transformer-only by Kijai. Full precision on 32GB VRAM.",
    recommendation: "BF16 variant of v1.0 distilled. Use v1.1 BF16 for latest quality.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-fp8-v1",
    name: "LTX 2.3 Distilled FP8 v1 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v1 by Kijai. Earliest FP8 release, superseded by v3.",
    recommendation: "Previous version. Use FP8 v3 or v1.1 FP8 for better quality.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-fp8-v2",
    name: "LTX 2.3 Distilled FP8 v2 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_input_scaled_v2.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 distilled v2 by Kijai. Superseded by v3.",
    recommendation: "Previous version. Use FP8 v3 or v1.1 FP8 for better quality.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-fp8-scaled",
    name: "LTX 2.3 Distilled FP8 Scaled (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_fp8_scaled.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "FP8 scaled distilled by Kijai. Alternative FP8 quantization method.",
    recommendation: "Alternative FP8 quantization. Use v1.1 FP8 for latest quality.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-mxfp8",
    name: "LTX 2.3 Distilled MXFP8 (Kijai)",
    filename: "ltx-2.3-22b-distilled_transformer_only_mxfp8_block32.safetensors",
    size: "~25 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "MXFP8 block-32 distilled v1.0 by Kijai. Block-32 quantization format.",
    recommendation: "Previous v1.0 MXFP8. Use v1.1 MXFP8 for latest quality.",
    isNew: true,
  },
  // ── Official FP8 models (Lightricks) ─────────────────────────────────────
  {
    id: "ltx23-dev-fp8-official",
    name: "LTX 2.3 Dev FP8 (Official)",
    filename: "ltx-2.3-22b-dev-fp8.safetensors",
    size: "29.1 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-fp8",
    description: "Official FP8 dev model from Lightricks. 29.1GB, runs on 16GB VRAM.",
    badge: "Official FP8",
    recommendation: "Official FP8 from Lightricks. Alternative to Kijai's FP8 dev model.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-fp8-official",
    name: "LTX 2.3 Distilled FP8 (Official)",
    filename: "ltx-2.3-22b-distilled-fp8.safetensors",
    size: "29.5 GB",
    vram: 16,
    vramMax: 24,
    type: "fp8",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3-fp8",
    description: "Official FP8 distilled model from Lightricks. 8 steps, CFG=1.",
    badge: "Official FP8",
    recommendation: "Official FP8 distilled from Lightricks. Alternative to Kijai's FP8.",
    isNew: true,
  },
  // ── LoRA v1.1 ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-distilled-lora-384-11",
    name: "LTX 2.3 Distilled LoRA 384 v1.1 (Official)",
    filename: "ltx-2.3-22b-distilled-lora-384-1.1.safetensors",
    size: "7.61 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official distilled LoRA rank-384 v1.1. Use with dev model. Place in models/loras/.",
    badge: "v1.1 LoRA",
    recommendation: "Latest official LoRA. Pair with dev model for distilled-quality output.",
    isNew: true,
  },
  // ── LoRA v1.0 ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-distilled-lora-384",
    name: "LTX 2.3 Distilled LoRA 384 (Official)",
    filename: "ltx-2.3-22b-distilled-lora-384.safetensors",
    size: "~7.6 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Official distilled LoRA rank-384 v1.0. Pair with dev model. Place in models/loras/.",
    badge: "v1.0 LoRA",
    recommendation: "Previous v1.0 LoRA. Use v1.1 LoRA for latest quality.",
    isNew: true,
  },
  {
    id: "ltx23-distilled-lora-dynamic",
    name: "LTX 2.3 Distilled LoRA Dynamic r105 (Kijai)",
    filename: "ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors",
    size: "~2.5 GB",
    vram: 16,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Dynamic rank LoRA (avg rank 105) by Kijai. Pair with dev model. Place in models/loras/.",
    badge: "Dynamic LoRA",
    recommendation: "v1.0 dynamic LoRA. Use v1.1 dynamic LoRA (rank 111) for latest quality.",
    isNew: true,
  },
  // ── Upscalers ─────────────────────────────────────────────────────────────
  {
    id: "ltx23-spatial-upscaler-x15",
    name: "Spatial Upscaler x1.5",
    filename: "ltx-2.3-spatial-upscaler-x1.5-1.0.safetensors",
    size: "1.09 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Spatial upscaler x1.5 for two-stage pipelines. Place in models/latent_upscale_models/.",
    recommendation: "Use when x2 upscale is too aggressive. Gentler upscaling option.",
    isNew: true,
  },
  {
    id: "ltx23-temporal-upscaler",
    name: "Temporal Upscaler x2",
    filename: "ltx-2.3-temporal-upscaler-x2-1.0.safetensors",
    size: "262 MB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Temporal upscaler x2 for frame interpolation. Place in models/latent_upscale_models/.",
    recommendation: "Optional. Use to double frame count (e.g. 25→49 frames) for smoother motion.",
    isNew: true,
  },
  {
    id: "ltx23-spatial-upscaler-x2-11",
    name: "Spatial Upscaler x2 v1.1",
    filename: "ltx-2.3-spatial-upscaler-x2-1.1.safetensors",
    size: "~1 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Updated spatial upscaler x2 v1.1. Place in models/latent_upscale_models/.",
    badge: "v1.1",
    recommendation: "Updated upscaler. Prefer over v1.0 for better upscaling quality.",
    isNew: true,
  },
  // ── required for all setups ───────────────────────────────────────────────
  {
    id: "ltx23-spatial-upscaler",
    name: "Spatial Upscaler x2",
    filename: "ltx-2.3-spatial-upscaler-x2-1.0.safetensors",
    size: "~1 GB",
    vram: 4,
    type: "lora",
    hfUrl: "https://huggingface.co/Lightricks/LTX-2.3",
    description: "Spatial upscaler x2 for two-stage pipelines. Place in models/latent_upscale_models/.",
    recommendation: "Optional. Use in a two-stage pipeline to upscale output resolution after generation.",
  },
  {
    id: "ltx23-vae",
    name: "LTX 2.3 VAE",
    filename: "taeltx2_3.safetensors",
    size: "~0.5 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy/blob/main/vae/taeltx2_3.safetensors",
    description: "VAE by Kijai. Required for all ComfyUI workflows. Place in models/vae/.",
    badge: "Required",
    recommendation: "Required for all setups. Download this first regardless of your VRAM.",
  },
  // ── Audio / Video VAE & Text Encoder components (Kijai) ──────────────────
  {
    id: "ltx23-audio-vae",
    name: "LTX 2.3 Audio VAE (Kijai)",
    filename: "LTX23_audio_vae_bf16.safetensors",
    size: "~1 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Audio VAE for audio-conditioned video generation. Place in models/vae/. Enables audio-to-video workflows.",
    badge: "New: Audio",
    recommendation: "Required for audio-conditioned workflows. Unlocks new audio-to-video capability.",
    isNew: true,
  },
  {
    id: "ltx23-video-vae",
    name: "LTX 2.3 Video VAE (Kijai)",
    filename: "LTX23_video_vae_bf16.safetensors",
    size: "~1 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Standalone video VAE BF16 by Kijai. Alternative to taeltx2_3. Place in models/vae/.",
    recommendation: "Alternative VAE option. Use in workflows that require the separate BF16 VAE component.",
    isNew: true,
  },
  {
    id: "ltx23-text-projection",
    name: "LTX 2.3 Text Projection (Kijai)",
    filename: "ltx-2.3_text_projection_bf16.safetensors",
    size: "~0.5 GB",
    vram: 2,
    type: "lora",
    hfUrl: "https://huggingface.co/Kijai/LTX2.3_comfy",
    description: "Text projection BF16 component by Kijai. Place in models/text_encoders/.",
    recommendation: "Required for workflows using separate text encoder components.",
    isNew: true,
  },
];

export function getModelsForVram(vram: number): ModelVariant[] {
  return MODELS.filter((m) => m.vram <= vram && (m.vramMax === undefined || vram <= m.vramMax));
}
